#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Language Configuration for Sora2 Video Generator
Multi-language support: English & Vietnamese
"""

LANGUAGES = {
    # ========================================================================
    # ENGLISH
    # ========================================================================
    'en': {
        # Main tabs
        'tab_settings': '⚙️ Settings',
        'tab_image_to_video': '🖼️ Image-to-Video',
        'tab_text_to_video': '📝 Text-to-Video',
        'tab_character': '👤 Character Manager',
        
        # Settings Tab
        'language': 'Language',
        'select_language': 'Select Language',
        'profile_management': 'Profile Management',
        'profile_management_title': 'Profile Management',
        'create_profiles': 'Create Profiles',
        'create_profiles_button': 'Create Profiles',
        'max': 'Max',
        'view_profile_stats': 'View Profile Statistics',
        'profiles_active': 'Profiles: {} active',
        'profiles': 'Profiles',
        'active': 'active',
        'quota_today': 'Quota today',
        'quota': 'Quota',
        'today': 'today',
        'remaining': 'Remaining',
        'bearer_token': 'Bearer Token (Auto-Extract)',
        'bearer_token_auto': 'Bearer Token (Auto-Extract)',
        'token_management': 'Token Management (Fully Automatic)',
        'token_info': 'Token Management (Fully Automatic)',
        'tokens_auto_extracted': 'Tokens are AUTO-EXTRACTED when you login to browser',
        'tokens_extracted': 'Tokens are AUTO-EXTRACTED when you login to browser',
        'saved_to_profile': 'Saved to profile_tokens.json automatically',
        'saved_automatically': 'Saved to profile_tokens.json automatically',
        'always_fresh': 'Always fresh and up-to-date',
        'always_fresh_updated': 'Always fresh and up-to-date',
        'no_manual_action': 'No manual action needed!',
        'no_manual_needed': 'No manual action needed!',
        'extract_token_now': 'Extract Token NOW (Force)',
        'force_extract': 'Extract Token NOW (Force)',
        'use_if_token_not_extracted': 'Use if token not auto-extracted during login',
        'use_if_not_extracted': '(Use if token not auto-extracted during login)',
        'profile': 'Profile',
        'status': 'Status',
        'token_preview': 'Token Preview',
        'extracted': 'Extracted',
        
        # Browser Settings
        'browser_settings': 'Browser Settings',
        'browser_not_started': 'Browser not started',
        'browser_status': 'Browser not started',
        'profile_selection': 'Profile Selection',
        'profile_select': 'Profile Selection',
        'auto_rotate': 'Auto-rotate (system chooses available profile)',
        'auto_rotate_desc': 'Auto-rotate (system chooses available profile)',
        'manual': 'Manual',
        'manual_select': 'Manual:',
        'auto_system_manages': 'Auto: System manages profiles | Manual: You choose specific profile',
        'auto_manual_info': 'Auto: System manages profiles | Manual: You choose specific profile',
        'run_headless': 'Run in headless mode (no browser window)',
        'run_headless_mode': 'Run in headless mode (no browser window)',
        'start_browser': 'Start Browser & Open Sora',
        'start_open_sora': 'Start Browser & Open Sora',
        'check_login_status': 'Check Login Status',
        'check_login': 'Check Login Status',
        'stop_browser': 'Stop Browser',
        
        # Character Tab
        'add_character': 'Add Character',
        'character_library': 'Character Library',
        'character_info': 'Character Info',
        'stt': 'No.',
        'character_name': 'Character Name',
        'cameo_id': 'Cameo ID / Username',
        'description_optional': 'Description (optional)',
        'thumbnail_image': 'Thumbnail Image',
        'browse': 'Browse',
        'add_to_library': 'Add to Library',
        'statistics': 'Statistics',
        'total_characters': 'Total Characters',
        'public': 'Public',
        'private': 'Private',
        'storage': 'Storage',
        'refresh': 'Refresh',
        'delete_selected': 'Delete Selected',
        'import_to_i2v': 'Import to I2V',
        'import_to_t2v': 'Import to T2V',
        'search': 'Search',
        'clear': 'Clear',
        'search_hint': '(Search by name, username, or description)',
        'view': 'View',
        'delete': 'Delete',
        'no_image_selected': 'No image selected',
        'no_characters': 'No characters yet. Add one to get started!',
        'character_name_hint': 'e.g., Iron Man, Elsa',
        'cameo_id_hint': 'Start with @, e.g., @ironman2024',
        'description_hint': 'Describe character for easier search',
        'no_image': '[No Image]',
        'no_results': "No results for '{}'",
        'preview_error': 'Preview error',
        'import_count_to_i2v': 'Import {} to I2V',
        'import_count_to_t2v': 'Import {} to T2V',
        
        # Image-to-Video Tab
        'reference_images': 'Reference Images',
        'ref_images': 'Reference Images',
        'add_images': 'Add Images',
        'get_paths': 'Get Paths',
        'clear_images': 'Clear Images',
        'images': 'Images',
        'generation_settings': 'Generation Settings',
        'gen_settings': 'Generation Settings',
        'orientation': 'Orientation',
        'duration': 'Duration',
        'after_download': 'After Download',
        'draft_action': 'Draft Action',
        'draft_action_title': 'Draft Action:',
        'delete_draft': 'Delete Draft (default)',
        'delete_draft_default': 'Delete Draft (default)',
        'post_to_public': 'POST to Public (experimental)',
        'post_public': 'POST to Public',
        'both_remove_draft': 'Both options remove draft from drafts page',
        'post_requires_login': 'POST requires logged in browser',
        'post_requires_token': 'POST requires valid Bearer token',
        'delete_requires_token': 'DELETE requires bearer token',
        'prompts_title': 'Prompts',
        'import_txt': 'Import TXT',
        'import_excel': 'Import Excel',
        'import_json': 'Import JSON',
        'enter_prompt': 'Enter prompt:',
        'add_to_queue': 'Add to Queue',
        'start_gen': 'Start Generation',
        'start_generation': 'Start Generation',
        'stop': 'Stop',
        'select_all': 'Select All',
        'deselect_all': 'Deselect All',
        'clear_all': 'Clear All',
        'no_dot': 'No.',
        'ref_image': 'Ref Image',
        'prompt': 'Prompt',
        'video_preview': 'Video Preview',
        'actions': 'Actions',
        'gen_log': 'Generation Log',
        
        # Watermark-Free Download
        'download_no_watermark': 'Download video without watermark',
        'download_video_no_watermark': 'Download video without watermark',
        'wf_download': 'Download without watermark',
        'enable_wf': 'Enable watermark-free download (requires POST mode)',
        'only_works_post_mode': 'Only works with \'POST to Public\' mode',
        'wf_how_works': 'How it works:',
        'wf_only_post': 'Only works when \'POST to Public\' is selected',
        'videos_saved_to': 'Videos saved to: ./downloads_no_watermark',
        'wf_downloaded_to': 'Videos will be downloaded to: ./downloads_no_watermark',
        'wf_filename': 'Filename format: i2v_001_prompt_2025_01_15_14_30_45.mp4',
        'wf_background': 'Downloads run in background, independent of generation',
        'wf_api': 'Uses SaveSora API to remove watermark',
        'stats': 'Stats',
        'total': 'total',
        'completed': 'completed',
        'failed': 'failed',
        'pending': 'pending',
        
        # Video Merger
        'enable_video_merger': 'Enable auto-merge videos',
        'video_merger': 'Video Merger',
        'enable_merger': 'Enable auto-merge videos',
        'batch_size': 'Batch size',
        'videos_per_batch': 'videos/batch',
        'videos_batch': 'videos/batch',
        'auto_merge_downloaded': 'Auto-merge downloaded videos',
        'auto_merge': 'Auto-merge downloaded videos',
        'output': 'Output',
        'output_folder': 'Output: ./merged_videos',
        'merger_not_initialized': 'Merger: Not initialized',
        'merger_disabled': 'Merger: Disabled',
        'batches': 'batches',
        'merged': 'merged',
        'buffer': 'Buffer',
        
        # Download Directory
        'download_dir': 'Download Directory',
        'save_to': 'Save videos to:',
        'browse_btn': 'Browse...',
        
        # Text-to-Video Tab
        'motion_prompts': 'Motion Prompts',
        'enter_prompts': 'Enter prompts:',
        'import_to_queue': 'Import to Queue',
        'generation_log': 'Generation Log',
        
        # Common
        'ok': 'OK',
        'cancel': 'Cancel',
        'yes': 'Yes',
        'no': 'No',
        'success': 'Success',
        'error': 'Error',
        'warning': 'Warning',
        'info': 'Info',
        'close': 'Close',
        'save': 'Save',
        'load': 'Load',
        'settings': 'Settings',
        
        # Messages (English)
        'no_characters_selected': 'No characters selected!',
        'imported_to_prompt': 'Imported {} characters to {} prompt!',
        'usernames_added': 'Usernames added',
        'go_to_tab': 'Go to {} tab to generate videos.',
        'could_not_find_prompt': 'Could not find {} prompt field.',
        'copy_usernames_manually': 'Please copy these usernames manually:',
        'then_paste_into_prompt': 'Then paste into {} prompt field.',
        'no_prompts': 'No prompts in text area.',
        'please_add': 'Please:',
        'type_manually': '1. Type prompts manually, OR',
        'import_from': '2. Import from TXT/Excel/JSON',
        'using_excel_data': 'Using Excel data for {} prompts',
        'using_json_data': 'Using JSON data for {} prompts',
        'using_manual': 'Using manual input with UI settings',
        'added_prompts': 'Added {} prompts to queue',
        'settings_applied': 'Settings applied',
        'queue_empty': 'Queue is empty.',
        'clear_confirm': 'Clear all {} items from queue?',
        'cleared': 'Cleared',
        'queue_cleared': 'Queue cleared.',
        'invalid_profiles': 'Number of profiles must be at least 1.',
        'create_confirm': 'Create {} Chrome profiles?',
        'profiles_created': 'Profiles will be created in:',
        'each_profile_size': 'Each profile folder ~100MB.',
        'continue_q': 'Continue?',
        'profile_creation': 'Profile Creation',
        'creation_complete': 'Profile Creation Complete!',
        'created': 'Created',
        'location': 'Location',
        'no_browser': 'No Browser',
        'start_browser_first': 'Please start browser in Settings tab first!',
        'login_required': 'Login Required',
        'not_logged_in': 'Not logged in',
        'login_manually': 'Please login manually in browser,',
        'then_check': 'then click \'Check Login Status\' again.',
        'login_status': 'Login Status',
        'logged_in_success': 'Logged in!',
        'token_extraction': 'Token extraction in progress...',
        'check_log': 'Check log for details.',
        'browser_running': 'Browser Running',
        'browser_already': 'Browser already running. Restart?',
        'no_profile': 'No Profile',
        'select_or_create': 'Select a profile or create profiles first.',
        'all_exhausted': 'All profiles exhausted.',
        'wait_tomorrow': 'Wait until tomorrow (quota resets)',
        'create_more': 'Create more profiles',
        'upgrade_license': 'Upgrade license',
        'browser_started': 'Browser Started',
        'browser_with': 'Browser started with profile:',
        'mode': 'Mode:',
        'generation_in_progress': 'Generation in progress!',
        'wait_complete': 'Please wait for current generation to complete.',
        'no_prompts_selected': 'No prompts selected for generation.',
        'quota_exhausted': 'Quota Exhausted',
        'all_quota_reached': 'All profiles have reached daily quota!',
        'total_profiles': 'Total profiles:',
        'used_today': 'Used today:',
        'daily_limit': 'Daily limit: 30 videos/profile',
        'solutions': 'Solutions:',
        'wait_quota_reset': 'Wait until tomorrow for quota reset',
        'upgrade_for_more': 'Upgrade license for more profiles',
        'contact': 'Contact: Zalo 0789.535.888',
        'confirm_generation': 'Confirm Generation',
        'generate_videos': 'Generate {} videos?',
        'mode_i2v': 'Mode: Image-to-Video',
        'selected': 'Selected',
        'prompts': 'prompts',
        'current_profile': 'Current profile:',
        'remaining_quota': 'Remaining quota:',
        'estimated_time': 'Estimated time:',
        'minutes': 'minutes',
        'important': 'IMPORTANT:',
        'keep_browser': 'Keep browser open during generation',
        'stable_internet': 'Stable internet required',
        'auto_switch': 'Auto-switch profiles when quota reached',
        'each_video': 'Each video takes 5-15 minutes',
        'post_mode': 'POST Mode:',
        'published': 'Videos will be published to public',
        'requires_token': 'Requires valid Bearer token',
        'generation_cancelled': 'Generation cancelled by user',
        'browser_required': 'Browser Required',
        'login_timeout': 'Login timeout or failed.',
        'try_again': 'Please try again.',
        'batch_finished': 'Batch finished!',
        'total_processed': 'Total processed:',
        'import_success': 'Import Complete!',
        'format': 'Format:',
        'imported': 'Imported:',
        'skipped': 'Skipped:',
        'invalid_entries': 'invalid entries',
        'file': 'File:',
        'draft_action_note': 'POST requires logged in browser\nDELETE requires bearer token',
        'wf_stats_initial': 'Stats: 0 total | 0 completed | 0 failed',
        'prompt_column': 'Prompt',
        'status_column': 'Status',
        'actions_column': 'Actions',
        'status_pending': 'Pending',
        'status_processing': 'Processing',
        'status_failed': 'Failed',
        'status_success': 'Success',
        'stopping_generation': 'Stopping generation...',
        'play': 'Play',
        'regen': 'Regen',
        'regenerate': 'Regenerate',
    },
    
    # ========================================================================
    # VIETNAMESE (TIẾNG VIỆT)
    # ========================================================================
    'vi': {
        # Main tabs
        'tab_settings': '⚙️ Cài đặt',
        'tab_image_to_video': '🖼️ Ảnh sang Video',
        'tab_text_to_video': '📝 Text sang Video',
        'tab_character': '👤 Quản lý Nhân vật',
        
        # Settings Tab
        'language': 'Ngôn ngữ',
        'select_language': 'Chọn ngôn ngữ',
        'profile_management': 'Quản lý Profile',
        'profile_management_title': 'Quản lý Profile',
        'create_profiles': 'Tạo Profiles',
        'create_profiles_button': 'Tạo Profiles',
        'max': 'Tối đa',
        'view_profile_stats': 'Xem thống kê Profile',
        'profiles_active': 'Profiles: {} đang hoạt động',
        'profiles': 'Profiles',
        'active': 'hoạt động',
        'quota_today': 'Quota hôm nay',
        'quota': 'Quota',
        'today': 'hôm nay',
        'remaining': 'Còn lại',
        'bearer_token': 'Bearer Token (Tự động)',
        'bearer_token_auto': 'Bearer Token (Tự động)',
        'token_management': 'Quản lý Token (Hoàn toàn tự động)',
        'token_info': 'Quản lý Token (Hoàn toàn tự động)',
        'tokens_auto_extracted': 'Token được TỰ ĐỘNG lấy khi bạn đăng nhập trình duyệt',
        'tokens_extracted': 'Token được TỰ ĐỘNG lấy khi bạn đăng nhập trình duyệt',
        'saved_to_profile': 'Lưu vào profile_tokens.json tự động',
        'saved_automatically': 'Lưu vào profile_tokens.json tự động',
        'always_fresh': 'Luôn mới và cập nhật',
        'always_fresh_updated': 'Luôn mới và cập nhật',
        'no_manual_action': 'Không cần thao tác thủ công!',
        'no_manual_needed': 'Không cần thao tác thủ công!',
        'extract_token_now': 'Lấy Token NGAY (Ép buộc)',
        'force_extract': 'Lấy Token NGAY (Ép buộc)',
        'use_if_token_not_extracted': 'Dùng nếu token không tự động lấy khi đăng nhập',
        'use_if_not_extracted': '(Dùng nếu token không tự động lấy)',
        'profile': 'Profile',
        'status': 'Trạng thái',
        'token_preview': 'Xem trước Token',
        'extracted': 'Đã lấy',
        
        # Browser Settings
        'browser_settings': 'Cài đặt Browser',
        'browser_not_started': 'Browser chưa khởi động',
        'browser_status': 'Browser chưa khởi động',
        'profile_selection': 'Chọn Profile',
        'profile_select': 'Chọn Profile',
        'auto_rotate': 'Tự động (hệ thống chọn profile khả dụng)',
        'auto_rotate_desc': 'Tự động (hệ thống chọn profile khả dụng)',
        'manual': 'Thủ công',
        'manual_select': 'Thủ công:',
        'auto_system_manages': 'Tự động: Hệ thống quản lý | Thủ công: Bạn chọn profile cụ thể',
        'auto_manual_info': 'Tự động: Hệ thống quản lý | Thủ công: Bạn chọn profile cụ thể',
        'run_headless': 'Chạy ẩn (không hiện cửa sổ trình duyệt)',
        'run_headless_mode': 'Chạy ẩn (không hiện cửa sổ trình duyệt)',
        'start_browser': 'Khởi động Browser & Mở Sora',
        'start_open_sora': 'Khởi động Browser & Mở Sora',
        'check_login_status': 'Kiểm tra trạng thái đăng nhập',
        'check_login': 'Kiểm tra đăng nhập',
        'stop_browser': 'Dừng Browser',
        
        # Character Tab
        'add_character': 'Thêm Nhân vật',
        'character_library': 'Thư viện Nhân vật',
        'character_info': 'Thông tin Nhân vật',
        'stt': 'STT',
        'character_name': 'Tên nhân vật',
        'cameo_id': 'Cameo ID / Username',
        'description_optional': 'Mô tả (tùy chọn)',
        'thumbnail_image': 'Ảnh đại diện',
        'browse': 'Chọn file',
        'add_to_library': 'Thêm vào thư viện',
        'statistics': 'Thống kê',
        'total_characters': 'Tổng nhân vật',
        'public': 'Công khai',
        'private': 'Riêng tư',
        'storage': 'Dung lượng',
        'refresh': 'Làm mới',
        'delete_selected': 'Xóa đã chọn',
        'import_to_i2v': 'Import vào I2V',
        'import_to_t2v': 'Import vào T2V',
        'search': 'Tìm kiếm',
        'clear': 'Xóa',
        'search_hint': '(Tìm theo tên, username hoặc mô tả)',
        'view': 'Xem',
        'delete': 'Xóa',
        'no_image_selected': 'Chưa chọn ảnh',
        'no_characters': 'Chưa có nhân vật nào. Thêm nhân vật để bắt đầu!',
        'character_name_hint': 'VD: Iron Man, Elsa',
        'cameo_id_hint': 'Bắt đầu với @, VD: @ironman2024',
        'description_hint': 'Mô tả nhân vật để dễ tìm kiếm',
        'no_image': '[Không có ảnh]',
        'no_results': "Không tìm thấy kết quả cho '{}'",
        'preview_error': 'Lỗi xem trước',
        'import_count_to_i2v': 'Import {} vào I2V',
        'import_count_to_t2v': 'Import {} vào T2V',
        
        # Image-to-Video Tab
        'reference_images': 'Ảnh tham khảo',
        'ref_images': 'Ảnh tham khảo',
        'add_images': 'Thêm ảnh',
        'get_paths': 'Lấy đường dẫn',
        'clear_images': 'Xóa ảnh',
        'images': 'Ảnh',
        'generation_settings': 'Cài đặt tạo video',
        'gen_settings': 'Cài đặt tạo video',
        'orientation': 'Hướng',
        'duration': 'Thời lượng',
        'after_download': 'Sau khi tải về',
        'draft_action': 'Hành động với Draft',
        'draft_action_title': 'Hành động với Draft:',
        'delete_draft': 'Xóa Draft (mặc định)',
        'delete_draft_default': 'Xóa Draft (mặc định)',
        'post_to_public': 'ĐĂNG công khai (thử nghiệm)',
        'post_public': 'ĐĂNG công khai',
        'both_remove_draft': 'Cả 2 tùy chọn đều xóa draft khỏi trang drafts',
        'post_requires_login': 'ĐĂNG yêu cầu đăng nhập trình duyệt',
        'post_requires_token': 'ĐĂNG yêu cầu Bearer token hợp lệ',
        'delete_requires_token': 'XÓA yêu cầu bearer token',
        'prompts_title': 'Prompts',
        'import_txt': 'Import TXT',
        'import_excel': 'Import Excel',
        'import_json': 'Nhập JSON',
        'enter_prompt': 'Nhập prompt:',
        'add_to_queue': 'Thêm vào hàng đợi',
        'start_gen': 'Bắt đầu tạo',
        'start_generation': 'Bắt đầu tạo',
        'stop': 'Dừng',
        'select_all': 'Chọn tất cả',
        'deselect_all': 'Bỏ chọn tất cả',
        'clear_all': 'Xóa tất cả',
        'no_dot': 'STT',
        'ref_image': 'Ảnh tham khảo',
        'prompt': 'Prompt',
        'video_preview': 'Xem trước',
        'actions': 'Thao tác',
        'gen_log': 'Log tạo video',
        
        # Watermark-Free Download
        'download_no_watermark': 'Tải video không watermark',
        'download_video_no_watermark': 'Tải video không watermark',
        'wf_download': 'Tải không watermark',
        'enable_wf': 'Bật tải không watermark (cần chế độ POST)',
        'only_works_post_mode': 'Chỉ hoạt động với chế độ \'ĐĂNG công khai\'',
        'wf_how_works': 'Cách hoạt động:',
        'wf_only_post': 'Chỉ hoạt động khi chọn \'ĐĂNG công khai\'',
        'videos_saved_to': 'Video lưu tại: ./downloads_no_watermark',
        'wf_downloaded_to': 'Video sẽ được tải về: ./downloads_no_watermark',
        'wf_filename': 'Định dạng tên: i2v_001_prompt_2025_01_15_14_30_45.mp4',
        'wf_background': 'Tải về chạy nền, độc lập với quá trình tạo',
        'wf_api': 'Sử dụng SaveSora API để xóa watermark',
        'stats': 'Thống kê',
        'total': 'tổng',
        'completed': 'hoàn thành',
        'failed': 'thất bại',
        'pending': 'đang chờ',
        
        # Video Merger
        'enable_video_merger': 'Bật tự động gộp video',
        'video_merger': 'Gộp Video',
        'enable_merger': 'Bật tự động gộp video',
        'batch_size': 'Kích thước lô',
        'videos_per_batch': 'video/lô',
        'videos_batch': 'video/lô',
        'auto_merge_downloaded': 'Tự động gộp video đã tải',
        'auto_merge': 'Tự động gộp video đã tải',
        'output': 'Đầu ra',
        'output_folder': 'Đầu ra: ./merged_videos',
        'merger_not_initialized': 'Merger: Chưa khởi tạo',
        'merger_disabled': 'Merger: Đã tắt',
        'batches': 'lô',
        'merged': 'đã gộp',
        'buffer': 'Bộ đệm',
        
        # Download Directory
        'download_dir': 'Thư mục tải về',
        'save_to': 'Lưu video vào:',
        'browse_btn': 'Chọn...',
        
        # Text-to-Video Tab
        'motion_prompts': 'Prompt chuyển động',
        'enter_prompts': 'Nhập prompts:',
        'import_to_queue': 'Nhập vào hàng đợi',
        'generation_log': 'Log tạo video',
        
        # Common
        'ok': 'OK',
        'cancel': 'Hủy',
        'yes': 'Có',
        'no': 'Không',
        'success': 'Thành công',
        'error': 'Lỗi',
        'warning': 'Cảnh báo',
        'info': 'Thông tin',
        'close': 'Đóng',
        'save': 'Lưu',
        'load': 'Tải',
        'settings': 'Cài đặt',
        
        # Messages (Vietnamese)
        'no_characters_selected': 'Chưa chọn nhân vật nào!',
        'imported_to_prompt': 'Đã nhập {} nhân vật vào {} prompt!',
        'usernames_added': 'Usernames đã thêm',
        'go_to_tab': 'Vào tab {} để tạo video.',
        'could_not_find_prompt': 'Không tìm thấy trường prompt {}.',
        'copy_usernames_manually': 'Vui lòng copy các usernames này thủ công:',
        'then_paste_into_prompt': 'Sau đó paste vào trường prompt {}.',
        'no_prompts': 'Không có prompts trong ô text.',
        'please_add': 'Vui lòng:',
        'type_manually': '1. Gõ prompts thủ công, HOẶC',
        'import_from': '2. Nhập từ TXT/Excel/JSON',
        'using_excel_data': 'Sử dụng dữ liệu Excel cho {} prompts',
        'using_json_data': 'Sử dụng dữ liệu JSON cho {} prompts',
        'using_manual': 'Sử dụng nhập thủ công với cài đặt UI',
        'added_prompts': 'Đã thêm {} prompts vào hàng đợi',
        'settings_applied': 'Đã áp dụng cài đặt',
        'queue_empty': 'Hàng đợi trống.',
        'clear_confirm': 'Xóa tất cả {} mục khỏi hàng đợi?',
        'cleared': 'Đã xóa',
        'queue_cleared': 'Hàng đợi đã được xóa.',
        'invalid_profiles': 'Số lượng profiles phải ít nhất là 1.',
        'create_confirm': 'Tạo {} Chrome profiles?',
        'profiles_created': 'Profiles sẽ được tạo trong:',
        'each_profile_size': 'Mỗi thư mục profile khoảng ~100MB.',
        'continue_q': 'Tiếp tục?',
        'profile_creation': 'Tạo Profile',
        'creation_complete': 'Tạo Profile Hoàn Tất!',
        'created': 'Đã tạo',
        'location': 'Vị trí',
        'no_browser': 'Không có Browser',
        'start_browser_first': 'Vui lòng khởi động browser trong tab Cài đặt!',
        'login_required': 'Yêu cầu đăng nhập',
        'not_logged_in': 'Chưa đăng nhập',
        'login_manually': 'Vui lòng đăng nhập thủ công trong trình duyệt,',
        'then_check': 'sau đó click \'Kiểm tra trạng thái đăng nhập\' lại.',
        'login_status': 'Trạng thái đăng nhập',
        'logged_in_success': 'Đã đăng nhập!',
        'token_extraction': 'Đang lấy token...',
        'check_log': 'Kiểm tra log để biết chi tiết.',
        'browser_running': 'Browser Đang Chạy',
        'browser_already': 'Browser đang chạy. Khởi động lại?',
        'no_profile': 'Không có Profile',
        'select_or_create': 'Chọn một profile hoặc tạo profiles trước.',
        'all_exhausted': 'Tất cả profiles đã hết quota.',
        'wait_tomorrow': 'Đợi đến ngày mai (quota sẽ reset)',
        'create_more': 'Tạo thêm profiles',
        'upgrade_license': 'Nâng cấp license',
        'browser_started': 'Browser Đã Khởi Động',
        'browser_with': 'Browser đã khởi động với profile:',
        'mode': 'Chế độ:',
        'generation_in_progress': 'Đang tạo video!',
        'wait_complete': 'Vui lòng đợi quá trình tạo hiện tại hoàn thành.',
        'no_prompts_selected': 'Không có prompts nào được chọn để tạo.',
        'quota_exhausted': 'Hết Quota',
        'all_quota_reached': 'Tất cả profiles đã đạt quota hàng ngày!',
        'total_profiles': 'Tổng profiles:',
        'used_today': 'Đã dùng hôm nay:',
        'daily_limit': 'Giới hạn hàng ngày: 30 video/profile',
        'solutions': 'Giải pháp:',
        'wait_quota_reset': 'Đợi đến ngày mai để quota reset',
        'upgrade_for_more': 'Nâng cấp license để có thêm profiles',
        'contact': 'Liên hệ: Zalo 0789.535.888',
        'confirm_generation': 'Xác nhận tạo video',
        'generate_videos': 'Tạo {} video?',
        'mode_i2v': 'Chế độ: Ảnh sang Video',
        'selected': 'Đã chọn',
        'prompts': 'prompts',
        'current_profile': 'Profile hiện tại:',
        'remaining_quota': 'Quota còn lại:',
        'estimated_time': 'Thời gian ước tính:',
        'minutes': 'phút',
        'important': 'QUAN TRỌNG:',
        'keep_browser': 'Giữ trình duyệt mở trong suốt quá trình tạo',
        'stable_internet': 'Cần kết nối internet ổn định',
        'auto_switch': 'Tự động chuyển profiles khi hết quota',
        'each_video': 'Mỗi video mất 5-15 phút',
        'post_mode': 'Chế độ POST:',
        'published': 'Video sẽ được đăng công khai',
        'requires_token': 'Yêu cầu Bearer token hợp lệ',
        'generation_cancelled': 'Đã hủy tạo video',
        'browser_required': 'Cần Browser',
        'login_timeout': 'Hết thời gian đăng nhập hoặc thất bại.',
        'try_again': 'Vui lòng thử lại.',
        'batch_finished': 'Lô đã hoàn thành!',
        'total_processed': 'Tổng đã xử lý:',
        'import_success': 'Nhập Hoàn Tất!',
        'format': 'Định dạng:',
        'imported': 'Đã nhập:',
        'skipped': 'Đã bỏ qua:',
        'invalid_entries': 'mục không hợp lệ',
        'file': 'File:',
        'draft_action_note': 'POST yêu cầu đăng nhập trình duyệt\nDELETE yêu cầu bearer token',
        'wf_stats_initial': 'Thống kê: 0 tổng | 0 hoàn thành | 0 thất bại',
        'prompt_column': 'Prompt',
        'status_column': 'Trạng thái',
        'actions_column': 'Thao tác',
        'status_pending': 'Đang chờ',
        'status_processing': 'Đang xử lý',
        'status_failed': 'Thất bại',
        'status_success': 'Thành công',
        'stopping_generation': 'Đang dừng tạo video...',
        'play': 'Phát',
        'regen': 'Tạo lại',
        'regenerate': 'Tạo lại',
    }
}


class LanguageManager:
    """Quản lý ngôn ngữ giao diện"""
    
    def __init__(self):
        self.current_lang = 'en'
        self.callbacks = []
    
    def set_language(self, lang_code: str):
        """Đổi ngôn ngữ"""
        if lang_code in LANGUAGES:
            self.current_lang = lang_code
            # Notify all registered callbacks
            for callback in self.callbacks:
                callback(lang_code)
    
    def get(self, key: str, default: str = None) -> str:
        """Lấy text theo ngôn ngữ hiện tại"""
        return LANGUAGES[self.current_lang].get(key, default or key)
    
    def register_callback(self, callback):
        """Đăng ký callback khi đổi ngôn ngữ"""
        self.callbacks.append(callback)
    
    def get_available_languages(self):
        """Lấy danh sách ngôn ngữ"""
        return {
            'en': 'English',
            'vi': 'Tiếng Việt'
        }


# Global instance
lang_manager = LanguageManager()